name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      # 4️⃣ Run pre-commit auto-fix (ignore exit code)
      - name: Run pre-commit auto-fix
        run: |
          pre-commit run --all-files

      # 5️⃣ Lint check (flake8)
      - name: Run flake8
        run: flake8 src tests

      # 6️⃣ Test (pytest)
      - name: Run pytest
        run: pytest tests
