name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      # Run pre-commit auto-fix (ignore exit code)
      - name: Run pre-commit auto-fix
        run: |
          pre-commit run --all-files

      # Lint check (flake8)
      - name: Run flake8
        run: flake8 src tests

      # Test (pytest)
      - name: Run pytest
        run: pytest tests
